[env:Esp32dev]
platform = espressif32
; build_src_filter = +<main.cpp>
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/version.py
monitor_speed = 115200
monitor_echo = yes
monitor_filters = 
    -esp32_exception_decoder
    -time
lib_ldf_mode = deep
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_INVERSION_OFF=1
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=34
    -DTFT_MOSI=26
    -DTFT_SCLK=25
    -DTFT_CS=13
    -DTFT_DC=27
    -DTFT_RST=14
    -DTFT_BL=12
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
    ; -DLDR_DEBUG
    ; -DTOUCH_DEBUG
    ; --- GUIslice demo ---
    -DUSER_CONFIG_LOADED=1
    -DDRV_DISP_TFT_ESPI
    -DDRV_TOUCH_HANDLER
    -DDEBUG_ERR=1
    -DGSLC_USE_PROGMEM=0
    -DGSLC_USE_FLOAT=0
    -DGSLC_LOCAL_STR=0
    -DGSLC_LOCAL_STR_LEN=30
    -DGSLC_TOUCH_MAX_EVT=1
    -DGSLC_CLIP_EN=1
    -DGSLC_BMP_TRANS_EN=1
    -DGSLC_BMP_TRANS_RGB=0xFF,0x00,0xFF
    -DGSLC_FEATURE_COMPOUND=1
    -DGSLC_FEATURE_XTEXTBOX_EMBED=0
    -DGSLC_FEATURE_INPUT=0
    -DGSLC_SD_EN=0
    -DGSLC_DEV_TOUCH=\"\"
    -DGSLC_ROTATE=1
    -DTOUCH_CS=23
lib_deps =
    bodmer/TFT_eSPI
    https://github.com/tanmaywankar/Grobot_Animations.git
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
    https://github.com/ImpulseAdventure/GUIslice.git