#!/usr/bin/env python3
"""
pbm_to_gslc_c.py — wrap a P4 PBM stream in GUIslice 1bpp C array boilerplate.

Reads binary PBM (P4) from stdin (typically piped from ImageMagick), emits
a .c file matching Image2C's output format byte-for-byte.

Usage (inside icon_prep.sh):
    convert IN.png ... pbm:- | pbm_to_gslc_c.py --name foo --src foo.png > foo.c
"""
import argparse
import os
import sys


WIKI_URL = "https://github.com/ImpulseAdventure/GUIslice/wiki/Display-Images-from-FLASH"
COMMENT_COL = 100         # column to align trailing `// 0x____ ...` comments
BYTES_PER_LINE = 16


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", required=True,
                   help="C array name (e.g. back_40x40px)")
    p.add_argument("--src", required=True,
                   help="Source filename for header comment (e.g. back_40x40px.png)")
    p.add_argument("--fg", default="FFFFFF",
                   help="Foreground colour as RRGGBB hex (default: FFFFFF)")
    return p.parse_args()


def read_pbm(stream):
    """Read P4 binary PBM from stream. Returns (width, height, data_bytes)."""
    magic = stream.readline().strip()
    if magic != b"P4":
        sys.exit(f"error: expected P4 PBM, got {magic!r}")
    # Skip comment lines, find dimensions
    while True:
        line = stream.readline().strip()
        if line and not line.startswith(b"#"):
            break
    width, height = map(int, line.split())
    data = stream.read()
    expected = ((width + 7) // 8) * height
    if len(data) != expected:
        sys.exit(f"error: expected {expected} data bytes, got {len(data)}")
    return width, height, data


def format_data_lines(data):
    """Format byte data as C array lines with Image2C-style trailing offset comments."""
    lines = []
    total = len(data)
    for i in range(0, total, BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        end_offset = i + len(chunk)
        bytes_str = ", ".join(f"0x{b:02X}" for b in chunk)
        # Trailing comma for all but the final chunk
        if end_offset < total:
            bytes_str += ","
        padding = max(1, COMMENT_COL - len(bytes_str))
        # Image2C labels these "pixels" though they're bytes — preserve quirk
        line = f"{bytes_str}{' ' * padding}// 0x{end_offset:04X} ({end_offset}) pixels"
        lines.append(line)
    return lines


def emit(name, src, width, height, data, fg_rgb):
    r, g, b = fg_rgb
    mem_size = len(data)
    out = []
    out.append("//" + "-" * 78)
    out.append("// File Generated by GUIslice_Image2C")
    out.append("//" + "-" * 78)
    out.append(f"// Generated from   : {src}")
    out.append(f"// Dimensions       : {width}x{height} pixels")
    out.append("// Bits Per Pixel   : 1 Bits")
    out.append(f"// Memory Size      : {mem_size} Bytes")
    out.append("// Little Endian    : true")
    out.append("//" + "-" * 78)
    out.append("")
    out.append("// For details on how to generate this file please refer to")
    out.append(f"// {WIKI_URL}")
    out.append("")
    out.append('#include "GUIslice.h"')
    out.append('#include "GUIslice_config.h"')
    out.append("")
    out.append("#if (GSLC_USE_PROGMEM)")
    out.append("  #if defined(__AVR__)")
    out.append("    #include <avr/pgmspace.h>")
    out.append("  #else")
    out.append("    #include <pgmspace.h>")
    out.append("  #endif")
    out.append("#endif")
    out.append("")
    out.append(f"const unsigned char {name}[{mem_size}+7] GSLC_PMEM = {{")
    # 16-bit big-endian height + width, each split into two byte literals
    out.append(f"0x{(height >> 8) & 0xFF:02X}, // Height of image")
    out.append(f"0x{height & 0xFF:02X},")
    out.append(f"0x{(width >> 8) & 0xFF:02X}, // Width of image")
    out.append(f"0x{width & 0xFF:02X},")
    # RGB foreground colour as right-aligned decimal (matches Image2C style)
    out.append(f"{r:3d}, // red color")
    out.append(f"{g:3d}, // green color")
    out.append(f"{b:3d}, // blue color")
    out.extend(format_data_lines(data))
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    args = parse_args()
    # Parse foreground hex
    fg_hex = args.fg.lstrip("#")
    if len(fg_hex) != 6:
        sys.exit("error: --fg must be 6-hex-digit RRGGBB")
    fg_rgb = tuple(int(fg_hex[i:i+2], 16) for i in (0, 2, 4))

    width, height, data = read_pbm(sys.stdin.buffer)
    c_source = emit(args.name, args.src, width, height, data, fg_rgb)
    sys.stdout.write(c_source)


if __name__ == "__main__":
    main()
