# Generates include/version.h from git describe at build time.
# Auto-runs via platformio.ini extra_scripts hook.

import os
import subprocess

Import("env")

def get_firmware_version():
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.SubprocessError):
        pass
    return "unknown"

version = get_firmware_version()
print(f"Building firmware version: {version}")

new_content = (
    "// Auto-generated by scripts/version.py - do not edit\n"
    "#pragma once\n"
    f'#define FW_VERSION "{version}"\n'
)

header_path = os.path.join(env["PROJECT_DIR"], "include", "version.h")
existing = ""
if os.path.exists(header_path):
    with open(header_path) as f:
        existing = f.read()

if existing != new_content:
    with open(header_path, "w") as f:
        f.write(new_content)