#pragma once
#include "GUIslice.h"

// GUIslice gui state lives in MenuCallbacks.cpp (single TU defining test_GSLC.h's globals)
extern gslc_tsGui m_gui;

// Generated by Builder; defined in test_GSLC.h
extern void InitGUIslice_gen();


extern void initMenuIcons();
// Page IDs — must match enum order in test_GSLC.h.
// Update when redesigning menus in Builder.
static const int16_t MENU_PG_ROOT = 0;   // E_PG_MAIN

extern void refreshStatsText();